tabelog-django/tabelogDjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tabelogapp.urls')),
]

tabelog-django/tabelogapp/urls.py
from django.urls import path
from . import views

app_name = 'tabelogapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search', views.Search, name='search'),
    path('shop_info/<str:restid>', views.ShopInfo, name='shop_info'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

tabelog-django/tabelogapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    category_l = models.CharField("業態カテゴリ", max_length=10, blank=False)
    name = models.CharField("業態名", max_length=30, blank=False)

    def __str__(self):
        return str(self.name)

class Pref(models.Model):
    pref = models.CharField("都道府県コード", max_length=6, blank=False)
    name = models.CharField("都道府県名", max_length=10, blank=False)

    def __str__(self):
        return str(self.name)

tabelog-django/tabelogapp/forms.py
from django import forms
from .models import Category, Pref, User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class SearchForm(forms.Form):
    selected_pref = forms.ModelChoiceField(
        label='都道府県',
        required=False,
        queryset=Pref.objects,
    )
    selected_category = forms.ModelChoiceField(
        label='業態',
        required=False,
        queryset=Category.objects,
    )
    freeword = forms.CharField(min_length = 2, max_length = 100, label='', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        selected_pref = self.fields['selected_pref']
        selected_category = self.fields['selected_category']

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

tabelog-django/tabelogapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.views import LoginView, LogoutView

from .models import Pref, Category
from .forms import SearchForm, SignUpForm, LoginForm
from django.contrib.auth import login, authenticate
import json
import requests
import environ

env = environ.Env()
env.read_env('.env')
GURUNABI_ACCESS_KEY=env('DJANGO_GURUNABI_ACCESS_KEY')
DJANGO_YAHOO_MAP_API_KEY=env('DJANGO_YAHOO_MAP_API_KEY')

def get_keyid():
    return GURUNABI_ACCESS_KEY

class IndexView(TemplateView):
    template_name = 'tabelogapp/index.html'

    def get_context_data(self, *args, **kwargs):
        searchform = SearchForm()
        params = {
            'searchform': searchform,
            }
        return params


def Search(request):
    if request.method == 'GET':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            category_l = request.GET['category_l']
            pref = request.GET['pref']
            freeword = request.GET['freeword']
            query = get_gnavi_data("", category_l, pref, freeword, 10)
            res_list = rest_search(query)
            total_hit_count = len(res_list)
            # 4. 整形した情報をリスト形式で保存し、paramsの一要素として渡す
            restaurants_info = extract_restaurant_info(res_list)

    params = {
        'total_hit_count': total_hit_count,
        'restaurants_info': restaurants_info,
        }

    return render (request, 'tabelogapp/search.html', params)

def ShopInfo(request, restid):
    keyid = get_keyid()
    id = restid
    query = get_gnavi_data(id, "", "", "", 1)
    res_list = rest_search(query)
    restaurants_info = extract_restaurant_info(res_list)

    params = {
        'title': '店舗詳細',
        'restaurants_info': restaurants_info,
        'map_api_key': DJANGO_YAHOO_MAP_API_KEY
        }

    return render (request, 'tabelogapp/shop_info.html', params)

class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'tabelogapp/signup.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('tabelogapp:index')
        return render(request, 'tabelogapp/signup.html', {'form': form})

class Login(LoginView):
    form_class = LoginForm
    template_name = 'tabelogapp/login.html'

class Logout(LogoutView):
    template_name = 'tabelogapp/logout.html'




def get_gnavi_data(id, category_l, pref, freeword, hit_per_page):
    keyid = get_keyid()
    # 一度に取得できる最大件数
    hit_per_page = hit_per_page
    # 店舗のid（グルナビ内で一意になっている）
    id = id
    # 大業態カテゴリ
    category_l = category_l
    #pref
    pref = pref
    #Freeword
    freeword = freeword
    #今回は関東地方のみ（コール回数を少なくするため）
    area = "AREA110"
    #パラメータ設定
    query = {"keyid": keyid, "id":id, "area":area, "pref":pref, "category_l":category_l,"hit_per_page":hit_per_page, "freeword":freeword}

    return query


def rest_search(query):
    res_list = []
    res = json.loads(requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/", params=query).text)
    # レスポンスがerror でない場合に処理を開始する
    if "error" not in res:
        res_list.extend(res["rest"])
    return res_list


def extract_restaurant_info(restaurants: 'restaurant response') -> 'restaurant list':
    restaurant_list = []
    for restaurant in restaurants:
        id = restaurant["id"]
        name = restaurant["name"]
        name_kana = restaurant["name_kana"]
        url = restaurant["url"]
        url_mobile = restaurant["url_mobile"]
        shop_image1 = restaurant["image_url"]["shop_image1"]
        shop_image2 = restaurant["image_url"]["shop_image2"]
        address = restaurant["address"]
        tel = restaurant["tel"]
        station_line = restaurant["access"]["line"]
        station = restaurant["access"]["station"]
        latitude = restaurant["latitude"]
        longitude = restaurant["longitude"]
        pr_long = restaurant["pr"]["pr_long"]

        restaurant_list.append([id, name, name_kana, url, url_mobile, shop_image1, shop_image2, address, tel, station_line, station, latitude, longitude, pr_long])
    return restaurant_list

tabelog-django/tabelogapp/templates/base.html
{% load static %}

<!doctype html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- オリジナルのCSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    {% block script%}{% endblock script %}
    {% block css%}{% endblock css %}
    <title>食べナビ</title>
  </head>
  <body>
    <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-right">
        <a class="navbar-brand" href="{% url 'tabelogapp:index' %}">食べナビ</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'tabelogapp:index' %}">TOP<span class="sr-only">(current)</span></a>
              </li>
            </ul>

            <ul class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
              <li>
                <a class="nav-item nav-link" href="{% url 'tabelogapp:logout' %}">ログアウト</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-item nav-link" href="{% url 'tabelogapp:login' %}">ログイン</a>
              </li>
              <li>
                <a class="nav-item nav-link" href="{% url 'tabelogapp:signup' %}">新規ユーザ登録</a>
              </li>
              {% endif %}
            </ul>

            <form method="GET" action="{% url 'tabelogapp:search' %}" name="searchform">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                    <select class="form-control nav-link" name="pref">
                        <option value="">都道府県</option>
                        {% for item in pref_list %}
                        <option value="{{item.pref}}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                    </li>
                    <li class="nav-item">
                    <select class="form-control nav-link" name="category_l">
                        <option value="">カテゴリ</option>
                        {% for item in category_list %}
                        <option value="{{item.category_l}}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                    </li>
                    <li class="nav-item">
                        <input class="form-control nav-link" type="text" placeholder="フリーワード" aria-label="Search" name="freeword">
                    </li>
                    <span>　</span>
                    <li class="nav-item">
                        <button type="submit" class="btn common-btn">Search</button>
                    </li>
                </ul>
            </form>
        </div>
    </nav>


    {% block content %}
    {% endblock %}


    <br><br>
    <!-- フッター -->
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <br/><br/>
                <hr/>
                <p>tabenavi</p>
                <a href="https://api.gnavi.co.jp/api/scope/" target="_blank">
                  <img src="https://techpit-market-prod.s3.amazonaws.com/uploads/part_attachment/file/4391/7c3eb00e-9f2a-407d-9705-eeba36fdb47a.gif" width="265" height="65" border="0" alt="グルメ情報検索サイト　ぐるなび">
                </a>
                <br/><br/>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

tabelog-django/tabelogapp/templates/tabelogapp/base.html
{% load static %}

<!doctype html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- オリジナルのCSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    {% block script%}{% endblock script %}
    {% block css%}{% endblock css %}
    <title>食べナビ</title>
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-right">
        <a class="navbar-brand" href="{% url 'techapp:index' %}">食べナビ</a>
        <div class="collapse navbar-collapse navbar-right" id="navbarNav">
            <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li>
                    <a class="nav-item nav-link" href="">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="">ログイン</a>
                </li>
                <li>
                    <a class="nav-item nav-link" href="">新規ユーザ登録</a>
                </li>
            {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}


    <br><br>
    <!-- フッター -->
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <br/><br/>
                <hr/>
                <p>tabenavi</p>
                <a href="https://api.gnavi.co.jp/api/scope/" target="_blank">
                  <img src="https://techpit-market-prod.s3.amazonaws.com/uploads/part_attachment/file/4391/7c3eb00e-9f2a-407d-9705-eeba36fdb47a.gif" width="265" height="65" border="0" alt="グルメ情報検索サイト　ぐるなび">
                </a>
                <br/><br/>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

tabelog-django/tabelogapp/templates/tabelogapp/index.html
{% load static %}

<!doctype html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-right">
        <a class="navbar-brand" href="{% url 'tabelogapp:index' %}">食べナビ</a>
        <div class="collapse navbar-collapse navbar-right" id="navbarNav">
            <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li>
                    <a class="nav-item nav-link" href="{% url 'tabelogapp:logout' %}">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'tabelogapp:login' %}">ログイン</a>
                </li>
                <li>
                    <a class="nav-item nav-link" href="{% url 'tabelogapp:signup' %}">新規ユーザ登録</a>
                </li>
            {% endif %}
            </ul>
        </div>
    </nav>

    <section class="search">
        <div id="top_carousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'image/topimage1.jpg' %}" class="d-block w-100" height="500px" alt="今日はどこで食べようか？">
                    <div class="carousel-caption" style="top:50px">
                        <h1><br>今日はどこで食事しよう？</h1>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'image/topimage2.jpg' %}" class="d-block w-100" height="500px">
                    <div class="carousel-caption" style="top:50px">
                        <h1><br>リアルな口コミNo.1！</h1>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'image/topimage3.jpg' %}" class="d-block w-100" height="500px">
                    <div class="carousel-caption" style="top:50px">
                        <h1><br>行きたいお店の<br>リアルな評判は？</h1>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#top_carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#top_carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </section>

    <section class="search-sec">
        <div class="container">
            <form method="GET" action="{% url 'tabelogapp:search' %}" name="searchform">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                <select class="form-control search-slt" name="pref">
                                    <option value="">都道府県</option>
                                    {% for item in pref_list %}
                                    <option value="{{item.pref}}">{{ item.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                            <select class="form-control search-slt" name="category_l">
                                <option value="">カテゴリ</option>
                                {% for item in category_list %}
                                <option value="{{item.category_l}}">{{ item.name }}</option>
                                {% endfor %}
                            </select>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                <input class="form-control search-slt" type="text" placeholder="フリーワード" aria-label="Search" name="freeword">
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                <button type="submit" class="btn search-btn">検索</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>

    <br><br>
    <!-- フッター -->
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <br/><br/>
                <hr/>
                <p>tabenavi</p>
                <a href="https://api.gnavi.co.jp/api/scope/" target="_blank">
                  <img src="https://techpit-market-prod.s3.amazonaws.com/uploads/part_attachment/file/4385/da4fdb59-83b0-4488-aeba-8bc8af038624.gif" width="265" height="65" border="0" alt="グルメ情報検索サイト　ぐるなび">
                </a>
                <br/><br/>
            </div>
        </div>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

tabelog-django/tabelogapp/templates/tabelogapp/login.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock css %}

{% block content %}
<div class="container">
    <div class="loginPage_contents">
        <h1 class="h3 loginPage_contents_title">ログイン</h1>
        <br><hr><br>
        <form action="" method="POST">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <p>{{ field.label}}</p>
                            {{ field }}
                            {{ field.errors }}
                            <hr>
                        {% endfor %}
                        <button type="submit" class="btn common-btn" >ログイン</button>
                        <input type="hidden" name="next" value="{{ next }}" />
                        {% csrf_token %}
                    </div>
                </div>
            </div>
        </form>
        <Hr>
            <p>まだアカウントがない方は<a href="{% url 'tabelogapp:signup' %}">こちら</a>。</p>
    </div>
</div>
{% endblock %}

tabelog-django/tabelogapp/templates/tabelogapp/logout.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock css %}

{% block script %}
{% endblock script %}

{% block content %}
<div class="container">
    <div class="loginPage_contents">
        <h1 class="h3 loginPage_contents_title">またのご利用をお待ちしております。</h1>
        <br><br><br>
        <a href="{% url 'tabelogapp:login' %}">ログインページへ</a>
    </div>

</div>
{% endblock %}

tabelog-django/tabelogapp/templates/tabelogapp/search.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
{% endblock css %}

{% block content %}
<div class="container">
    <div class="row">
    {% if restaurants_info %}
        <h3>{{ total_hit_count }}件あります。<small>最大10件表示</small></h3>
        <br><br>
        {% for item in restaurants_info %}
        <div class="col-md-12">
            <div class="section-outer-box">
                <div class="row">
                    <div class="col-xs-3 col-md-3">
                        <img src="{{ item.5 }}" alt="{{ item.1 }}" class="img-rounded img-responsive" width="150px" />
                    </div>
                    <div class="col-xs-9 col-md-9 section-box">
                        <h4>{{ item.1 }}　<a href="{% url 'tabelogapp:shop_info' item.0 %}" class="btn common-btn">詳細を見る</a></h4>
                        <p>{{ item.2 }}</p>
                        <p>{{ item.7 }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="col-lg-12">
                <p>該当するものはありません。</p>
            </div>
        </div>
    {% endif %}
    </div>
</div>
{% endblock %}

tabelog-django/tabelogapp/templates/tabelogapp/shop_info.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="section-title">{{ restaurants_info.0.1 }}</h2>
        </div>
    </div>
    <br>

    <div class="row">
        <div class="col-md-4">
            <div id="shop_carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{{ restaurants_info.0.5 }}" class="d-block w-100" alt="{{ restaurants_info.0.1 }}">
                    </div>
                    {% if restaurants_info.0.6 %}
                    <div class="carousel-item">
                        <img src="{{ restaurants_info.0.6 }}" class="d-block w-100" alt="{{ restaurants_info.0.1 }}">
                    </div>
                    {% endif %}
                </div>
                <a class="carousel-control-prev" href="#shop_carousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">前の画像</span>
                </a>
                <a class="carousel-control-next" href="#shop_carousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">次の画像</span>
                </a>
            </div>
            <br>

        </div>

        <div class="col-md-8">
            <p>{{ restaurants_info.0.13|linebreaksbr }}</p>
            <a href="{{ restaurants_info.0.3 }}" class="btn common-btn" target="_blank">お店ページ <i class="fas fa-external-link-alt"></i></a>
            <a href="{{ restaurants_info.0.4 }}" class="btn common-btn" target="_blank">お店ページ(モバイル) <i class="fas fa-external-link-alt"></i></a>

        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-md-12">
            <h2 class="section-title">店舗基本情報</h2>
            <table class="table">
                <tr>
                    <td>店舗名</td>
                    <td>{{ restaurants_info.0.1 }}</td>
                </tr>
                <tr>
                    <td>住所</td>
                    <td>{{ restaurants_info.0.7 }}</td>
                </tr>
                <tr>
                    <td>TEL</td>
                    <td>{{ restaurants_info.0.8 }}</td>
                </tr>
                <tr>
                    <td>アクセス</td>
                    <td>{{ restaurants_info.0.9 }} <br>{{ restaurants_info.0.10 }}</td>
                </tr>
                <tr>
                    <td>地図</td>
                    <td>
                        <div id="map" style="width:800px; height:600px"></div>
                        <script type="text/javascript" charset="utf-8" src="https://map.yahooapis.jp/js/V1/jsapi?appid={{ map_api_key }}"></script>
                        <script type="text/javascript">
                        window.onload = function(){
                            var ymap = new Y.Map("map");
                            ymap.drawMap(new Y.LatLng({{restaurants_info.0.11}}, {{ restaurants_info.0.12 }}), 17, Y.LayerSetId.NORMAL);
                        }
                        </script>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

{% endblock %}

tabelog-django/tabelogapp/templates/tabelogapp/signup.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock css %}

{% block content %}

<div class="container">
    <div class="loginPage_contents">
        <h1 class="h3 loginPage_contents_title">新規ユーザー登録</h1>
        <br><hr><br>
        <form action="" method="POST">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <p>{{ field.label}}</p>
                            {{ field }}
                            {{ field.errors }}
                            <hr>
                        {% endfor %}
                        <button type="submit" class="btn common-btn" >登録してログイン</button>
                        <input type="hidden" name="next" value="{{ next }}" />
                        {% csrf_token %}

                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}